Checks errors and lost code oh my

diff --git a/.trunk/setup-ci/action.yaml b/.trunk/setup-ci/action.yaml
--- a/.trunk/setup-ci/action.yaml
+++ b/.trunk/setup-ci/action.yaml
@@ -16,3 +16,12 @@ runs:
                 echo "Failed to install dependencies"
                 exit 1
               fi
+        - name: Install Docs NodeJS dependencies
+          shell: bash
+          working-directory: docs
+          run: |
+              npm ci --prefer-offline --no-audit --ignore-scripts
+              if [ $? -ne 0 ]; then
+                echo "Failed to install dependencies"
+                exit 1
+              fi
